### PR TITLE
Fixes rendering issue and some minor grammar

### LINKED ISSUE #89: Fix rendering list issue and TOC links in Troubleshooting
I'll submit a PR on these cosmetic changes shortly.

### PR DESCRIPTION
**Pull request by 00willo**
Closes #89 with:
* Adjusted TOC order to reflect the heading order in the page
* Fixed broken TOC links
* Normalised a couple of headings that were nested and shouldn't have been.
* Fixed markdown rendering where lists were not
* Minor grammar fixes.

### CODE REVIEW

**Comment by 00willo** [comment]
Ready for review.

**Comment by 00willo** [comment]
@frikky Would you like me to resolve these conflicts that have been introduced with the changes to the master branch after I submitted this PR, or will that handled by the person who merges?

**Comment by frikky** [comment]
> @frikky Would you like me to resolve these conflicts that have been introduced with the changes to the master branch after I submitted this PR, or will that handled by the person who merges?

Feel free to fix it 😊 Just realized I shouldve merged this first, before adding the new parts. Just need to read through and verify

**Comment by 00willo** [comment]
> Feel free to fix it

Done.

**Comment by frikky** [comment]
This was a nice cleanup. Not really sure what was happening around the "## Useful OpenSearch Queries" place, but this seems to make sense.

Thanks!

**Comment by 00willo** [comment]
> Not really sure what was happening around the "## Useful OpenSearch Queries" place, but this seems to make sense.

I was doing there was mainly around indenting the code blocks so the markdown rendering can take care of numbering the paragraphs automagically. The github UI doesn't show changes in an indent like that very well.  It appears like the whole piece is replaced with the same thing, but there's a subtle change in the spacing at th beginning of the line.

**Pull request merged**
