### PR TITLE
Troubleshooting instances running in swarm mode

### PR DESCRIPTION
**Pull request by DavidtheGoliath**

### CODE REVIEW

**Comment by azgaviperr** [comment]
for the workers I will have use docker service logs as command. If not this means you will have to go on local of each node to get logs of workers running on it. 

Or using something like swarmpit or portainer.

**Comment by DavidtheGoliath** [comment]
Precisely, let me clarify that in the docs. Thanks for the feedback : )

**Review by azgaviperr — CHANGES_REQUESTED** [review]
Maybe add a link to docker service logs https://docs.docker.com/engine/reference/commandline/service_logs/

**Comment by frikky** [comment]
I think this right here is crucial to be able to handle both docker, swarm & cloud troubleshooting well.

We'll have to look at better tracing options onprem at some point too, as this will get complex with swarm & k8s across many servers

**Pull request merged**
