### PR TITLE
Swarm mode improvements

### PR DESCRIPTION
**Pull request by 0x0elliot**

### CODE REVIEW

**Comment by 0x0elliot** [comment]
Ready for merge. Accept when you can. More docs to come for Shuffle swarm.

**Comment by 0x0elliot** [comment]
You know what? Let me add the swarm documentation in this PR itself.

**Comment by 0x0elliot** [comment]
Ready for merge

**Comment by frikky** [comment]
Nice - thanks @0x0elliot :)

**Pull request merged**
